### ISSUE TITLE
How to do inference?

### ISSUE THREAD

**Issue by bth5032** [Vision-CAIR/VisualGPT#10]
There doesn't appear to be any examples of how to do inference with this model. 

I'm pretty confused, in training you guys [feed in the entire label](https://github.com/Vision-CAIR/VisualGPT/blob/main/train_visualGPT.py#L40-L43) along with the image then use the label for the loss. What am I supposed to feed in if I have a new image?

Additionally, do I just use gpt2-large tokenizer to decode the model outputs?

**Comment by junchen14** [comment]
hi, the inference code is already integrated in the training process. 

if you wanna test new images, you can load the best-training model and only do the inference

->do I just use gpt2-large tokenizer to decode the model outputs?
yes, we use GPT-2 tokenizer to decode

**Comment by bth5032** [comment]
Hey thanks! I did manage to find [this function](https://github.com/Vision-CAIR/VisualGPT/blob/main/train_visualGPT.py#L54) which seems to use `model.beam_search` But I'm still digging through code to figure out how to drop in a new image loader. Is there an example anywhere of using a custom set of images on disk for inference? After I've trained the model, it would be nice to actually use it :)
