### ISSUE TITLE
About memory overflow error during training

### ISSUE THREAD

**Issue by Wangyf1998** [Vision-CAIR/VisualGPT#12]
Hi! Thanks for the code. When I train the model to 42 batch, I met with the  following error using 4*gtx2080ti:
“CUDA: out of memory, tried to allocate...” 
I set the batchsize = 10, it still occurs.  Is it totally a hardware problem? What device you use to train the model?
I notice that you said your code doesn't support multi-gpu training 1 years ago, is it still not supported yet?
Thank you!

**Comment by junchen14** [comment]
hi, it is because the code does not well support multi-gpu training. Sorry for this inconvenience!
