### ISSUE TITLE
Batch size in Evaluation Strategy

### ISSUE THREAD

**Issue by TCBpenta8** [Vision-CAIR/VisualGPT#3]
Hi,
Good to see a new idea in image captioning!

Here is my question. I noticed that in your evaluation stage, you input the sample one by one, that is in 'train_visualGPT.py' line 62. And also I found that you cast the batch size in validation and evaluation 5 times smaller than one in training.  Will there be a specific reason for these? As I notice that the evaluation actually supports mini-batch strategy, and your strategy will cost tons of time if the evaluation set is huge. 

I am kind of a freshman in this area so my question might be silly. Feel free to let me know what you think.

Regards,

**Comment by junchen14** [comment]
> Hi,
> Good to see a new idea in image captioning!
> 
> Here is my question. I noticed that in your evaluation stage, you input the sample one by one, that is in 'train_visualGPT.py' line 62. And also I found that you cast the batch size in validation and evaluation 5 times smaller than one in training. Will there be a specific reason for these? As I notice that the evaluation actually supports mini-batch strategy, and your strategy will cost tons of time if the evaluation set is huge.
> 
> I am kind of a freshman in this area so my question might be silly. Feel free to let me know what you think.
> 
> Regards,

hi

**Comment by junchen14** [comment]
> Hi,
> Good to see a new idea in image captioning!
> 
> Here is my question. I noticed that in your evaluation stage, you input the sample one by one, that is in 'train_visualGPT.py' line 62. And also I found that you cast the batch size in validation and evaluation 5 times smaller than one in training. Will there be a specific reason for these? As I notice that the evaluation actually supports mini-batch strategy, and your strategy will cost tons of time if the evaluation set is huge.
> 
> I am kind of a freshman in this area so my question might be silly. Feel free to let me know what you think.
> 
> Regards,

 you input the sample one by one, that is in 'train_visualGPT.py' line 62
-> it is not iterating the sample one by one, instead it is to iterate the samples batch by batch
also I found that you cast the batch size in validation and evaluation 5 times smaller than one in training. 
-> it is not very necessary to control the batch size into a very smaller number in the evaluation stage, we make it 5 times smaller just in order to avoid some potential memory issues, but actually it does not happen in the real cases

**Comment by TCBpenta8** [comment]
😂 Thank you for your reply!
