### ISSUE TITLE
Explaining the cross attention

### ISSUE THREAD

**Issue by TCBpenta8** [Vision-CAIR/VisualGPT#6]
Hi,

thank you for answering my last question!

I am currently trying to explain part of the caption generation process and I am interested in Figure.5 where you highlighted the visual scores on the generated captions. 

However, if my understanding is correct, you have not put any code about your explaining method in the repo. 
It will be really appreciated if you would like to give some coding example about the visualization for better understanding!

Cheers!

**Comment by junchen14** [comment]
Hi  thanks for raising this issue!

I will try to upload the related code in jupyter notebook these days.

**Comment by TCBpenta8** [comment]
Just a quick question. Would you mind giving a brief idea on how to extract the scores from the last cross attention layer?

I am currently trying to reproduce the explanation like in Figure 5. My idea is to pass and output the attention scores with the same pipeline as the generated token indices. However, I met the issue of how to pass the scores through the beam search algorithm. 

Is my idea generally correct? if yes then I may stick on it (but due to my heavy workload, I don't have too much effort, so ... ^ ^ I am still waiting for your notebook)

Thanks for your reply. Cheers

**Comment by junchen14** [comment]
sorry that we just found one of team members mistakenly delete the juputer notebook. We are trying to recover it right now.

In order to pass the scores through the beam search, we use the beam size of 1 instead.

**Comment by junchen14** [comment]
> Just a quick question. Would you mind giving a brief idea on how to extract the scores from the last cross attention layer?
> 
> I am currently trying to reproduce the explanation like in Figure 5. My idea is to pass and output the attention scores with the same pipeline as the generated token indices. However, I met the issue of how to pass the scores through the beam search algorithm.
> 
> Is my idea generally correct? if yes then I may stick on it (but due to my heavy workload, I don't have too much effort, so ... ^ ^ I am still waiting for your notebook)
> 
> Thanks for your reply. Cheers

let me know if you have any further questions with the implementation of attention visualization.  We will try to help you through it.
