### ISSUE TITLE
Variable mention before initialization

### ISSUE THREAD

**Issue by KaratzasBasil** [Vision-CAIR/VisualGPT#8]
https://github.com/Vision-CAIR/VisualGPT/blob/72d6b741da6ecdd626e486596bb5057f0ffb8511/train_visualGPT.py#L150

In line 150 of file train_visualGPT a variable named fp16 is mentioned. This variable was never initialized in the arguments

**Comment by junchen14** [comment]
Thanks for spotting this, `fp16` parameter was used in our previous experiment, but it turns out that it does not improve the speed much in our experiment, and hence we remove it out in our final version. 

Now we have removed this line in our code.
